# Generated by Django 5.0.6 on 2024-11-29 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0004_alter_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='last_otp_generated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
